#!/usr/bin/env sh
set -eu

go test ./...
go vet ./...
go build ./...
if command -v govulncheck >/dev/null 2>&1; then
  govulncheck ./...
fi
if command -v gosec >/dev/null 2>&1; then
  gosec ./...
fi
test -f migrations/000001_create_users.up.sql
test -f migrations/000001_create_users.down.sql
